name: tests.yml
on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: "Setup go"
        uses: actions/setup-go@v6
        with:
          go-version: stable

      - name: "Run tests storage"
        run: |
          cd tests/storage
          go test .
